[build]
  command = 'yarn build'
  publish = 'dist/'
  functions = 'dist_lambda/'

[template.environment]
    NODE_ENV='production'
    MAILGUN_API_KEY='Your MailGun API Key'
    MAILGUN_DOMAIN='example.com'
    MAILGUN_FROM='Full Name <fullname@example.com>'
    FAUNADB_SERVER_SECRET='Your FaunaDB Server Secret'
